import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const result = await build({
  entryPoints: [resolve(root, 'src/viewer/app.ts')],
  bundle: true,
  platform: 'browser',
  format: 'iife',
  target: ['es2022'],
  write: false,
  minify: false,
  sourcemap: false,
});

const source = result.outputFiles[0]?.text;
if (!source) throw new Error('Viewer bundle produced no JavaScript');
const output = resolve(root, 'src/viewer/app.generated.ts');
await mkdir(dirname(output), { recursive: true });
await writeFile(output, `// Generated by npm run viewer:build. Do not edit.\nexport const VIEWER_APP_JS = ${JSON.stringify(source)};\n`);
