/**
 * @file shared/protocolMessageTypes.ts
 *
 * Message type lists used by protocol guards for runtime validation.
 */

export const POPUP_TO_BG_MESSAGE_TYPES = [
  'START_RECORDING',
  'STOP_RECORDING',
  'DISCARD_RECORDING',
  'GET_RECORDING_STATUS',
  'GET_DRIVE_TOKEN',
  'SET_MIC_MUTED',
  'SET_CAMERA_MUTED',
  'SET_INPUT_DEVICE',
  'SET_PAUSED',
  'DISMISS_UPLOAD_JOB',
  'RETRY_UPLOAD_JOB',
  'CANCEL_UPLOAD_JOB',
  'SKIP_RECORDING_NAMING',
  'DISMISS_INTERRUPTION',
  'LIST_RECORDING_HISTORY',
  'RENAME_RECORDING_HISTORY',
  'SET_RECORDING_HISTORY_NOTE',
  'REMOVE_RECORDING_HISTORY',
  'OPEN_RECORDING_HISTORY_FILE',
  'MARK_NOTATION',
  'END_NOTATION',
  'LIST_ACTIVE_NOTATIONS',
  'UPDATE_ACTIVE_NOTATION',
  'REMOVE_ACTIVE_NOTATION',
  'LIST_RECORDING_NOTATIONS',
  'GET_RECORDING_PLAYBACK_MANIFEST',
  'FILE_RECORDING_TO_DESTINATION',
  'LIST_PENDING_LOCAL_DELIVERIES',
  'DELIVER_LOCAL_RECORDING',
  'PREPARE_RECORDING_PLAYBACK_SOURCE',
  'REFRESH_RECORDING_PLAYBACK_SOURCE',
  'LIST_RECORDING_NOTATION_SUMMARIES',
  'ADD_RECORDING_NOTATION',
  'UPDATE_RECORDING_NOTATION',
  'REMOVE_RECORDING_NOTATION',
] as const;

/** The subset of popup commands validated by `isRecordingHistoryMessage`. */
export const RECORDING_HISTORY_MESSAGE_TYPES = [
  'LIST_RECORDING_HISTORY',
  'RENAME_RECORDING_HISTORY',
  'SET_RECORDING_HISTORY_NOTE',
  'REMOVE_RECORDING_HISTORY',
  'OPEN_RECORDING_HISTORY_FILE',
] as const;

/** The subset of popup commands validated by `isRecordingNotationMessage`. */
export const RECORDING_NOTATION_MESSAGE_TYPES = [
  'MARK_NOTATION',
  'END_NOTATION',
  'LIST_ACTIVE_NOTATIONS',
  'UPDATE_ACTIVE_NOTATION',
  'REMOVE_ACTIVE_NOTATION',
  'LIST_RECORDING_NOTATIONS',
  'LIST_RECORDING_NOTATION_SUMMARIES',
  'ADD_RECORDING_NOTATION',
  'UPDATE_RECORDING_NOTATION',
  'REMOVE_RECORDING_NOTATION',
] as const;

/**
 * Popup commands whose failures answer `{ ok: false, error }` and must **not**
 * fail the recording session. Everything else is a capture command whose
 * failure *is* a session failure, so a data-plane message that is missing here
 * would take a live recording down with it.
 */
export const NON_SESSION_RESPONSE_MESSAGE_TYPES = [
  ...RECORDING_HISTORY_MESSAGE_TYPES,
  ...RECORDING_NOTATION_MESSAGE_TYPES,
] as const;

export const POPUP_TO_CONTENT_MESSAGE_TYPES = [
  'GET_TRANSCRIPT',
  'RESET_TRANSCRIPT',
  'GET_CAPTION_STATE',
] as const;

export const CONTENT_TO_BG_MESSAGE_TYPES = [
  'MEETING_ENDED',
] as const;

export const OFFSCREEN_TO_BG_MESSAGE_TYPES = [
  'OFFSCREEN_READY',
  'OFFSCREEN_STATE',
  'OFFSCREEN_UPLOAD_STATE',
  'OFFSCREEN_SAVE',
  'TELEMETRY_SNAPSHOT',
  'TELEMETRY_FLUSH',
] as const;

export const BG_TO_OFFSCREEN_RUNTIME_CONNECT = 'OFFSCREEN_CONNECT' as const;
export const PERF_EVENT_MESSAGE_TYPE = 'PERF_EVENT' as const;
export const TELEMETRY_RUN_MESSAGE_TYPE = 'TELEMETRY_RUN' as const;
